"""empty message

Revision ID: 10fc77dfa41d
Revises: f59208a74006
Create Date: 2021-04-06 12:39:09.482693

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '10fc77dfa41d'
down_revision = 'f59208a74006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
