"""empty message

Revision ID: 494ec1b530e7
Revises: c00e58578d50
Create Date: 2021-04-06 21:47:32.340874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494ec1b530e7'
down_revision = 'c00e58578d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
