"""empty message

Revision ID: 4976564f041e
Revises: 494ec1b530e7
Create Date: 2021-04-06 21:49:16.464634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4976564f041e'
down_revision = '494ec1b530e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
