"""empty message

Revision ID: 4f5dbe9502f5
Revises: d93e524a8bbe
Create Date: 2021-04-05 14:34:54.337585

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4f5dbe9502f5'
down_revision = 'd93e524a8bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_id', table_name='candidates')
    op.drop_index('ix_candidates_info', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_ballots_id', table_name='ballots')
    op.drop_index('ix_ballots_preference', table_name='ballots')
    op.drop_table('ballots')
    op.add_column('elections', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('elections_creator_id_fkey', 'elections', type_='foreignkey')
    op.create_foreign_key(None, 'elections', 'users', ['owner_id'], ['id'])
    op.drop_column('elections', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.create_foreign_key('elections_creator_id_fkey', 'elections', 'users', ['creator_id'], ['id'])
    op.drop_column('elections', 'owner_id')
    op.create_table('ballots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='ballots_election_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='ballots_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ballots_pkey')
    )
    op.create_index('ix_ballots_preference', 'ballots', ['preference'], unique=False)
    op.create_index('ix_ballots_id', 'ballots', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='candidates_election_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='candidates_pkey')
    )
    op.create_index('ix_candidates_info', 'candidates', ['info'], unique=False)
    op.create_index('ix_candidates_id', 'candidates', ['id'], unique=False)
    # ### end Alembic commands ###
