"""empty message

Revision ID: 91072a05036c
Revises: 88676c2fdaa1
Create Date: 2021-04-06 00:04:39.594600

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '91072a05036c'
down_revision = '88676c2fdaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference', sa.String(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ballots_id'), 'ballots', ['id'], unique=False)
    op.create_index(op.f('ix_ballots_preference'), 'ballots', ['preference'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_info'), 'candidates', ['info'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_info'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_ballots_preference'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_id'), table_name='ballots')
    op.drop_table('ballots')
    # ### end Alembic commands ###
