"""empty message

Revision ID: c2d5de2f3812
Revises: 91072a05036c
Create Date: 2021-04-06 12:13:46.547629

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c2d5de2f3812'
down_revision = '91072a05036c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
