"""empty message

Revision ID: f59208a74006
Revises: c2d5de2f3812
Create Date: 2021-04-06 12:21:35.991127

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f59208a74006'
down_revision = 'c2d5de2f3812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
